### ISSUE TITLE
Issue #02 - MVP List

### ISSUE THREAD

**Issue by keginzburg** [sodea1/FunTrails#2]
# MVP List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [X] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [X] Correctly formatted
  - [X] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments
Your schedule meets 10 days while you have a full 14 days available. Do you think you can get your 7 MVPs done in the shorter time frame?

1. Splash Page/ User Auth
    1. I would add a demo login piece of functionality here.
2. Trail Page
    1. I would specify here more details about your map functionality and maybe a small blurb about the technology you plan on using. Also, does this tech factor towards your search MVP as well?
3. Reviews
    1. Will users be able to leave photos with their reviews? Definitely slightly more challenging, but I would highly recommend you integrate this as well as AllTrails allows that functionality.
4. User Profile Page
    1. Honestly, I would replace this MVP with a Park MVP. Multiple trails can exist in separate parks and could be organized this way. A Profile Page is nice and definitely could integrate CRUD, but Profile Page might fit better as a Bonus MVP.
5. Search
    1. Again, how will your map technology factor in here?

**Comment by sodea1** [comment]
Thanks Kyle. Good things to think about. I'll revise.

**Comment by sodea1** [comment]
Can you clarify what you mean on #5-Search/map integration? I was envisioning using the last day or so to implement plain search bar functionality with autocomplete. AllTrails does have an explore page where the larger map exists but I didn't think I would be able to do that in the time alotted.

**Comment by keginzburg** [comment]
Sure. AllTrails does have its Explore functionality in which you can use its map to look at parks and trails and select them. Search Bar is definitely key for searching parks and trails as most users will utilize this, but after a text-based Search Bar is added, I would definitely attempt to utilize a map for "searching" as well. It can be slotted as a Bonus maybe?

**Comment by keginzburg** [comment]
To your previous comment regarding the map implementation, I am referring to the map used in Explore that can drag around and check trails out with.
