### ISSUE TITLE
Issue #03 - Schema

### ISSUE THREAD

**Issue by keginzburg** [sodea1/FunTrails#3]
# Database Schema
- [x] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [x] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [X] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table’s name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
1. Users
    1. index on first_name, unique: true here? Do we want this here?
2. Trails
    1. longitude and latitude, length: should these be integers or a float?
    2. park_id: is this a foreign key? If so, do we need to add that to details and should we index it?
    3. Do trails need a name? And if so and users are searching for trails by name, should we index their name column?
3. Parks
    1. longitude and latitude, acreage: should these be integers or a float?
    2. What will contact represent?
    3. Again, do parks have names too and should that column be indexed if people are searching for parks?
4. Reviews
    1. What will tag represent?
    2. Will reviews have unique photos added by the reviewer as well?
5. Photos
    1. How are you keeping track of photos on your backend? They currently have a primary key and foreign keys? Do they need something else?
    2. Do photos need both a park_id and trail_id? Or could they only use one of them? If so, which one?

**Comment by sodea1** [comment]
the index in users is on email

**Comment by sodea1** [comment]
contact represents a phone number

**Comment by sodea1** [comment]
tag in a review is the little descriptors that show up in the rectangle looking containers (i.e. Dog-friendly, hiking, muddy,, etc)

**Comment by sodea1** [comment]
ok I made a lot of changes with your feedback (thanks). #1 Did nothing, see first comment #2 made all changes #3 made all changes #4 added indexes on photos linked to a review #5 added associations to photos user

**Comment by keginzburg** [comment]
You still have a unique index on the first name row. Do we want someone's first name to be unique in your Users table? What if two different users with the same first name tried to make accounts?

**Comment by sodea1** [comment]
Thanks Kyle. I went back and corrected the first name index error. I also made some significant changes to the schema to store tags in a different table and establish a connection to trails via a joins table. 

Only follow up I have is in regards to your last point. I'm not sure I follow your thinking on the photo references.
